//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunOnceDurationOverride) DeepCopyInto(out *RunOnceDurationOverride) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunOnceDurationOverride.
func (in *RunOnceDurationOverride) DeepCopy() *RunOnceDurationOverride {
	if in == nil {
		return nil
	}
	out := new(RunOnceDurationOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunOnceDurationOverride) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunOnceDurationOverrideConfig) DeepCopyInto(out *RunOnceDurationOverrideConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunOnceDurationOverrideConfig.
func (in *RunOnceDurationOverrideConfig) DeepCopy() *RunOnceDurationOverrideConfig {
	if in == nil {
		return nil
	}
	out := new(RunOnceDurationOverrideConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunOnceDurationOverrideConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunOnceDurationOverrideConfigSpec) DeepCopyInto(out *RunOnceDurationOverrideConfigSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunOnceDurationOverrideConfigSpec.
func (in *RunOnceDurationOverrideConfigSpec) DeepCopy() *RunOnceDurationOverrideConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RunOnceDurationOverrideConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunOnceDurationOverrideList) DeepCopyInto(out *RunOnceDurationOverrideList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunOnceDurationOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunOnceDurationOverrideList.
func (in *RunOnceDurationOverrideList) DeepCopy() *RunOnceDurationOverrideList {
	if in == nil {
		return nil
	}
	out := new(RunOnceDurationOverrideList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunOnceDurationOverrideList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunOnceDurationOverrideResourceHash) DeepCopyInto(out *RunOnceDurationOverrideResourceHash) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunOnceDurationOverrideResourceHash.
func (in *RunOnceDurationOverrideResourceHash) DeepCopy() *RunOnceDurationOverrideResourceHash {
	if in == nil {
		return nil
	}
	out := new(RunOnceDurationOverrideResourceHash)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunOnceDurationOverrideResources) DeepCopyInto(out *RunOnceDurationOverrideResources) {
	*out = *in
	if in.ConfigurationRef != nil {
		in, out := &in.ConfigurationRef, &out.ConfigurationRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.ServiceCAConfigMapRef != nil {
		in, out := &in.ServiceCAConfigMapRef, &out.ServiceCAConfigMapRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.ServiceRef != nil {
		in, out := &in.ServiceRef, &out.ServiceRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.ServiceCertSecretRef != nil {
		in, out := &in.ServiceCertSecretRef, &out.ServiceCertSecretRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.DeploymentRef != nil {
		in, out := &in.DeploymentRef, &out.DeploymentRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.APiServiceRef != nil {
		in, out := &in.APiServiceRef, &out.APiServiceRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	if in.MutatingWebhookConfigurationRef != nil {
		in, out := &in.MutatingWebhookConfigurationRef, &out.MutatingWebhookConfigurationRef
		*out = new(corev1.ObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunOnceDurationOverrideResources.
func (in *RunOnceDurationOverrideResources) DeepCopy() *RunOnceDurationOverrideResources {
	if in == nil {
		return nil
	}
	out := new(RunOnceDurationOverrideResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunOnceDurationOverrideSpec) DeepCopyInto(out *RunOnceDurationOverrideSpec) {
	*out = *in
	in.OperatorSpec.DeepCopyInto(&out.OperatorSpec)
	out.RunOnceDurationOverrideConfig = in.RunOnceDurationOverrideConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunOnceDurationOverrideSpec.
func (in *RunOnceDurationOverrideSpec) DeepCopy() *RunOnceDurationOverrideSpec {
	if in == nil {
		return nil
	}
	out := new(RunOnceDurationOverrideSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunOnceDurationOverrideStatus) DeepCopyInto(out *RunOnceDurationOverrideStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Hash = in.Hash
	in.CertsRotateAt.DeepCopyInto(&out.CertsRotateAt)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunOnceDurationOverrideStatus.
func (in *RunOnceDurationOverrideStatus) DeepCopy() *RunOnceDurationOverrideStatus {
	if in == nil {
		return nil
	}
	out := new(RunOnceDurationOverrideStatus)
	in.DeepCopyInto(out)
	return out
}
