apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: run-once-duration-override-operator
  namespace: run-once-duration-override-operator
rules:
  # to have the power to ensure RBAC for the operand
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - create
      - update
      - patch
      - get

  # to have the power to read prioritylevelconfigurations
  - apiGroups:
      - flowcontrol.apiserver.k8s.io
    resources:
      - prioritylevelconfigurations
      - flowschemas
    verbs:
      - get
      - list
      - watch

  # to have the power to watch secondary resources
  - apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
      - services
      - serviceaccounts
      - pods
    verbs:
      - get
      - create
      - update
      - patch
      - list
      - watch

  # to have the power to watch secondary resources
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
    verbs:
      - create
      - get
      - update
      - patch
      - list
      - watch
